on: 
  push:
    branches: 
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build
      - run: version=$(npm pkg get version) && echo "version=${version//\"/}" >> $GITHUB_ENV
      - run: echo "time=$(date +%s)" >> $GITHUB_ENV
      - run: echo "git_commit=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - run: npm version prerelease --preid "dev.${{ env.time }}-${{ env.git_commit }}" --no-git-tag-version --allow-same-version
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: "dev"
      - run: npm deprecate "admin-side@dev" "This is a development version"
