on: 
  push:
    branches: 
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set version
        run: echo "version=$(npm pkg get version)" >> $GITHUB_ENV
      - name: Set time and commit
        run: echo "time=$(date +%s)" >> $GITHUB_ENV
      - name: Set commit
        run: echo "commit=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: "${{ env.version }}-dev.${{ env.time }}-${{ env.commit }}"
