on: 
  push:
    branches: 
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build
      - uses: JS-DevTools/npm-publish@v1
      env:
        version: 
          run: npm pkg get version
        commit: 
          run: git rev-parse --short HEAD
        timestamp: 
          run: date +%s
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: "${{ env.version }}-dev.${{ env.timestamp }}-${{ env.commit }}"
